import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, ArrowLeft, MapPin, Compass, Camera, Users, Globe2, Check, Copy, Plus, X, Upload, Link, LockKeyhole, Trophy, Flag, Trash2, ImagePlus, LoaderCircle, ChevronRight, Sparkles, MoveUpRight, LogOut } from 'lucide-react';
import { readPhotoLocation } from './photo-location';
import Map from './Map';
import LocationSearch from './LocationSearch';
import { api, json, preparePhoto, formatDistance } from './api';
import './styles.css';

function App() {
  const [route,setRoute] = useState(location.pathname);
  const [host,setHost] = useState(false), [ready,setReady] = useState(false);
  const [login,setLogin] = useState(false), [toast,setToast] = useState('');
  const notify = message => setToast(message);
  const navigate = path => { history.pushState({},'',path); setRoute(path); window.scrollTo(0,0); };
  useEffect(() => {
    const listener = () => setRoute(location.pathname);
    addEventListener('popstate', listener);
    const authenticate = () => {
      const key = new URLSearchParams(location.hash.slice(1)).get('host');
      if (key) history.replaceState({}, '', location.pathname);
      (key ? api('/host/session', json('POST', { key })) : api('/session'))
        .then(data => { setHost(data.host); if (key) notify('You’re signed in. Let’s make a trip.'); })
        .catch(e=>notify(e.message)).finally(()=>setReady(true));
    };
    authenticate();
    const onHash = () => { if (new URLSearchParams(location.hash.slice(1)).has('host')) authenticate(); };
    addEventListener('hashchange', onHash);
    return () => { removeEventListener('popstate', listener); removeEventListener('hashchange', onHash); };
  }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(()=>setToast(''),6000); return ()=>clearTimeout(timer); },[toast]);
  const create = () => host ? navigate('/create') : setLogin(true);
  return <>
    <header className="site-header"><div className="header-inner">
      <a className="brand" href="/" onClick={e=>{e.preventDefault();navigate('/');}}><span className="brand-icon"><MapPin size={22} strokeWidth={2}/></span>travelguesser<span className="brand-dot">.</span></a>
      <nav aria-label="Main navigation"><a className="how-link" href="/#how-it-works" onClick={e=>{if(route!=='/'){e.preventDefault();navigate('/');setTimeout(()=>document.getElementById('how-it-works')?.scrollIntoView({behavior:'smooth'}),100);}}}>How it works</a>{host && <button className="text-button trips-nav" onClick={()=>{navigate('/');setTimeout(()=>document.getElementById('my-trips')?.scrollIntoView({behavior:'smooth'}),100);}}>My trips</button>}<button className="button small" onClick={create}><Plus size={16}/> Create a trip</button></nav>
    </div></header>
    {!ready ? <div className="loading-page"><LoaderCircle className="spin"/> Unpacking…</div> : route === '/create' ? (host ? <CreateTrip navigate={navigate} notify={notify}/> : <div className="narrow-page"><LockKeyhole size={38}/><h1>Your next trip starts here.</h1><p>Open your private host link to start uploading photos.</p><button className="button" onClick={()=>setLogin(true)}>Enter host key <ArrowRight size={18}/></button></div>) : /^\/g\/[^/]+\/?$/.test(route) ? <Game key={route} id={route.split('/')[2]} navigate={navigate} notify={notify}/> : route === '/' ? <Home host={host} create={create} navigate={navigate} notify={notify}/> : <div className="narrow-page"><h1>A little off the map.</h1><p>We couldn’t find that page.</p><button className="button" onClick={()=>navigate('/')}>Back home</button></div>}
    <footer className="site-footer"><a href="/" onClick={e=>{e.preventDefault();navigate('/');}}><Compass size={16}/> A little closer, wherever you are.</a><span>Made for the group chat <span className="footer-star">✳</span></span>{host&&<button title="Sign out of hosting" className="icon-button" onClick={async()=>{await api('/host/session',{method:'DELETE'});setHost(false);navigate('/');}}><LogOut size={15}/></button>}</footer>
    {login&&<HostLogin close={()=>setLogin(false)} success={()=>{setHost(true);setLogin(false);navigate('/create');}}/>}
    {toast&&<div className="toast" role="status">{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
  </>;
}

function Home({host,create,navigate,notify}) {
  const [join,setJoin] = useState(''), [games,setGames] = useState([]), [loadError,setLoadError] = useState('');
  const [deleting,setDeleting] = useState(null);
  const load = () => api('/host/games').then(setGames).catch(e=>setLoadError(e.message));
  useEffect(()=>{if(host)load();},[host]);
  function joinGame(e) { e.preventDefault(); const raw=join.trim(); const id=raw.includes('/g/') ? raw.split('/g/')[1].split(/[?#/]/)[0] : raw; if(!/^[a-zA-Z0-9_-]{8,40}$/.test(id))return notify('Paste the trip link or code your friend sent you.');navigate(`/g/${id}`); }
  return <main className="home">
    <section className="hero">
      <div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> A WORLD OF MEMORIES. A GAME WITH FRIENDS.</div><h1>You were there.<br/>Can they <em>guess where?</em></h1><p className="hero-description">Turn your travel photos into a little friendly competition. Drop your memories, share a link, and see who knows your world best.</p><div className="hero-buttons"><button className="button primary-large" onClick={create}>Create a trip <ArrowUpRight size={21}/></button><button className="button outline primary-large" onClick={()=>navigate('/g/demo-trip')}><Compass size={19}/> Try a demo</button></div><div className="hero-note"><span className="tiny-avatars"><span>W</span><span>A</span><span>J</span></span><span>No accounts for friends. Just a link and a hunch.</span></div></div>
      <div className="hero-art" aria-label="A travel photo ready for your friends to guess"><svg className="flight-path" viewBox="0 0 650 500" aria-hidden="true"><path d="M45 355C-25 211 151 91 188 162S44 318 153 360s239-27 371-155"/><path d="m513 207 20-11-5 23"/></svg><div className="back-postcard"/><div className="postcard"><div className="postcard-image"><img src="/images/mountains.jpg" alt="Dramatic mountain peaks catching the evening light"/><span className="photo-label"><Camera size={13}/> FROM YOUR CAMERA ROLL</span><span className="photo-pin"><MapPin size={25}/></span></div><div className="postcard-caption"><span>Somewhere worth remembering.</span><span>01 / ∞</span></div></div><div className="stamp"><Globe2 size={34} strokeWidth={1}/><span>THE WORLD<br/>IS YOURS TO GUESS</span></div><div className="guess-note"><span className="guess-note-icon"><MapPin size={17}/></span><div><b>Okay, I know this one…</b><span>Famous last words.</span></div><span className="guess-emoji">↗</span></div><div className="handwritten">Big memories. Wild guesses.<svg viewBox="0 0 200 15"><path d="M1 8Q100 0 194 9M28 13Q118 5 169 12"/></svg></div></div>
    </section>
    <section id="how-it-works" className="how-section"><div className="section-intro"><span className="eyebrow">LESS SETUP. MORE “WAIT, IS THAT…?”</span><h2>From camera roll to friendly rivalry.</h2></div><div className="steps">
      <Step number="01" icon={Camera} title="Pack your photos" text="Pick a few trip highlights. We’ll read their GPS data, or you can pin the spot yourself."/>
      <Step number="02" icon={Link} title="Send the invitation" text="One trip, one link. Drop it in the group chat and let your friends jump right in."/>
      <Step number="03" icon={MapPin} title="Let the guessing begin" text="They explore the photo and drop a pin. The closer the guess, the bigger the bragging rights."/>
    </div></section>
    {host&&<section className="my-trips" id="my-trips"><div className="section-heading"><div><span className="eyebrow">YOUR TRAVEL JOURNAL</span><h2>Ready for a few guesses.</h2></div><button className="text-button" onClick={create}>New trip <Plus size={16}/></button></div>{loadError&&<p className="error" role="alert">{loadError}</p>}{games.length ? <div className="trip-grid">{games.map(game=><article className="trip-card" key={game.id}><div className="trip-card-icon"><MapPin size={26}/></div><div><span className="eyebrow">{game.rounds} PHOTO{game.rounds===1?'':'S'} · {new Date(game.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})}</span><h3>{game.title}</h3><p>Hosted by {game.hostName}</p></div><div className="trip-card-actions"><button className="button outline small" onClick={()=>copyLink(game.id,notify)}><Copy size={15}/> Invite</button><button className="icon-button" aria-label={`Open ${game.title}`} onClick={()=>navigate(`/g/${game.id}`)}><ArrowUpRight size={20}/></button><button className="icon-button" aria-label={`Delete ${game.title}`} onClick={()=>setDeleting(game)}><Trash2 size={16}/></button></div></article>)}</div> : <div className="empty-trips"><Camera size={25}/><p>Your next adventure belongs here.</p><button className="text-button" onClick={create}>Create your first trip <ArrowRight size={16}/></button></div>}</section>}
    <section className="invite-strip"><div className="invite-icon"><Users size={24}/></div><div><h3>Got an invitation?</h3><p>Your friend’s adventure is one link away.</p></div><form onSubmit={joinGame}><label className="sr-only" htmlFor="trip-link">Trip link or code</label><input id="trip-link" value={join} onChange={e=>setJoin(e.target.value)} placeholder="Paste a trip link or code" required/><button className="button" type="submit">Join trip <ArrowRight size={17}/></button></form></section>
    {deleting&&<Modal close={()=>setDeleting(null)} title="Delete this trip?"><p>“{deleting.title}” and its photos and scores will be deleted. Its invite link will stop working.</p><div className="modal-actions"><button className="button outline" onClick={()=>setDeleting(null)}>Keep trip</button><button className="button danger" onClick={async()=>{try{await api(`/games/${deleting.id}`,{method:'DELETE'});setDeleting(null);load();notify('Trip deleted.');}catch(e){notify(e.message);}}}>Delete trip</button></div></Modal>}
  </main>;
}

function Step({number,icon:Icon,title,text}) { return <article className="step"><div className="step-top"><span className="step-icon"><Icon size={23} strokeWidth={1.6}/></span><span className="step-number">{number}</span></div><h3>{title}</h3><p>{text}</p></article>; }

function Modal({close,title,children}) {
  const ref=useRef(null);
  useEffect(()=>{const old=document.activeElement;const el=ref.current;el?.focus();const fn=e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const all=[...el.querySelectorAll('button, input, a, select, textarea, [tabindex="0"]')].filter(x=>!x.disabled);if(!all.length)return;const first=all[0],last=all.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===el)){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',fn);return()=>{document.removeEventListener('keydown',fn);old?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close();}}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title" tabIndex={-1} ref={ref}><button className="modal-close icon-button" onClick={close} aria-label="Close dialog"><X size={20}/></button><span className="modal-symbol"><Compass size={27}/></span><h2 id="modal-title">{title}</h2>{children}</section></div>;
}

function HostLogin({close,success}) {
  const [key,setKey]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <Modal close={close} title="Unlock trip creation"><p>Only hosts can upload photos and manage trips. Open your private host link to sign in automatically, or paste the link or key below.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const value=key.trim();const hostKey=value.includes('#')?new URLSearchParams(value.slice(value.indexOf('#')+1)).get('host'):value;if(!hostKey)throw new Error('Paste your private host link or host key.');await api('/host/session',json('POST',{key:hostKey}));success();}catch(e){setError(e.message);}finally{setBusy(false);}}}><label htmlFor="host-key">Private host link or key</label><input id="host-key" type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="Paste your private link or key" required autoComplete="off"/>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<LockKeyhole size={17}/>} Start creating trips</button></form><p className="small-note">The app owner has the private host link. Friends only need a trip’s invitation link to play.</p></Modal>;
}

async function copyLink(id,notify) { try{await navigator.clipboard.writeText(`${location.origin}/g/${id}`);notify('Invite link copied. Time to wake up the group chat.');}catch{notify('Copy the trip link from your address bar or the share box.');} }

function CreateTrip({navigate,notify}) {
  const [photos,setPhotos]=useState([]),[selected,setSelected]=useState(0),[title,setTitle]=useState(''),[hostName,setHostName]=useState(localStorage.getItem('tg_host_name')||'');
  const [busy,setBusy]=useState(false),[preparing,setPreparing]=useState(false),[error,setError]=useState(''),[created,setCreated]=useState(null),[drag,setDrag]=useState(false);
  const input=useRef(null), photoRef=useRef(photos); photoRef.current=photos;
  useEffect(()=>()=>photoRef.current.forEach(p=>URL.revokeObjectURL(p.url)),[]);
  const current=photos[selected];
  const update = changes => setPhotos(list=>list.map((p,i)=>i===selected?{...p,...changes}:p));
  async function addFiles(files) {
    if(preparing)return;
    setPreparing(true);setError('');
    const allowed=[...files].slice(0,12-photos.length);
    if(files.length>allowed.length)notify('A trip can have up to 12 photos.');
    const added=[];
    for(const file of allowed){try{const metadata=await readPhotoLocation(file);const prepared=await preparePhoto(file);added.push({...prepared,...metadata,id:crypto.randomUUID(),name:file.name,caption:''});}catch(e){setError(e.message);}}
    setPhotos(list=>[...list,...added]);if(added.length)setSelected(photos.length);setPreparing(false);
  }
  async function publish(e){
    e.preventDefault();setBusy(true);setError('');
    const form=new FormData();form.append('metadata',JSON.stringify({title,hostName,photos:photos.map(p=>({...p.location,caption:p.caption}))}));photos.forEach(p=>form.append('photos',p.file,'photo.jpg'));
    try{const game=await api('/games',{method:'POST',body:form});localStorage.setItem('tg_host_name',hostName);setCreated(game);}catch(e){setError(e.message);}finally{setBusy(false);}
  }
  const missing=photos.filter(p=>!p.location).length;
  if(created)return <main className="narrow-page created-page"><span className="success-icon"><Check size={35}/></span><span className="eyebrow">LET THE FRIENDLY RIVALRY BEGIN</span><h1>Your trip is<br/><em>ready to go.</em></h1><p>“{created.title}” has {created.rounds} {created.rounds===1?'memory':'memories'} waiting to be placed on the map. Send the link to your friends.</p><div className="share-box"><input aria-label="Trip invite link" readOnly value={`${location.origin}/g/${created.id}`} onFocus={e=>e.target.select()}/><button className="button" onClick={()=>copyLink(created.id,notify)}><Copy size={17}/> Copy link</button></div><div className="center-buttons"><button className="button outline" onClick={()=>navigate(`/g/${created.id}`)}>Open trip <ArrowUpRight size={17}/></button><button className="text-button" onClick={()=>navigate('/')}>Back to my trips</button></div><p className="small-note"><LockKeyhole size={14}/> Anyone with this trip link can play and see its photos.</p></main>;
  return <main className="create-page"><button className="back-link" onClick={()=>navigate('/')}><ArrowLeft size={16}/> Back to your travels</button><div className="page-heading"><div><span className="eyebrow">THE BEST SOUVENIRS ARE STORIES</span><h1>Make it <em>a trip.</em></h1><p>A few photos. A few pins. A whole lot of “I’ve been there!”</p></div><span className="page-badge"><Camera size={17}/> 1–12 photos per trip</span></div>
    <form onSubmit={publish}><div className="trip-details panel"><div className="section-number">01</div><div className="field"><label htmlFor="title">Give your trip a name</label><input id="title" placeholder="e.g. A summer worth getting lost in" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={80}/></div><div className="field host-name"><label htmlFor="name">Your name</label><input id="name" placeholder="Who’s behind the camera?" value={hostName} onChange={e=>setHostName(e.target.value)} required maxLength={30}/></div></div>
    <div className="upload-heading"><div><span className="section-number">02</span><h2>Unpack your camera roll</h2></div><span>{photos.length} / 12 photos</span></div>
    <input type="file" accept="image/jpeg,image/png,image/webp" multiple ref={input} className="sr-only" aria-label="Upload travel photos" onChange={e=>{addFiles(e.target.files);e.target.value='';}}/>
    {!photos.length ? <button type="button" className={`dropzone ${drag?'dragging':''}`} onClick={()=>input.current.click()} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);addFiles(e.dataTransfer.files);}} disabled={preparing}><span className="drop-icon">{preparing?<LoaderCircle className="spin" size={30}/>:<ImagePlus size={30} strokeWidth={1.5}/>}</span><h3>{preparing?'Getting your photos ready…':'Drop a little adventure here'}</h3><p>Drag photos here, or <span>browse your files</span></p><small>JPG, PNG or WebP · Up to 25 MB each · GPS detected automatically</small></button> : <div className="photo-workspace panel"><div className="photo-rail">{photos.map((p,i)=><button type="button" key={p.id} className={`photo-thumb ${selected===i?'selected':''}`} onClick={()=>setSelected(i)} aria-label={`Edit photo ${i+1}${p.location?', location set':', needs a location'}`}><img src={p.url} alt={`Trip photo ${i+1}`}/><span className="thumb-number">{i+1}</span><span className={`thumb-status ${p.location?'set':''}`}>{p.location?<Check size={11}/>:<MapPin size={11}/>}</span></button>)}{photos.length<12&&<button type="button" className="add-photo" onClick={()=>input.current.click()} disabled={preparing} aria-label="Add more photos">{preparing?<LoaderCircle className="spin" size={23}/>:<Plus size={23}/>}<span>Add photos</span></button>}</div>
    {current&&<div className="photo-editor"><div className="photo-preview"><img src={current.url} alt={`Selected trip photo ${selected+1}`}/><button type="button" className="remove-photo" onClick={()=>{URL.revokeObjectURL(current.url);setPhotos(p=>p.filter((_,i)=>i!==selected));setSelected(s=>Math.max(0,s-1));}}><Trash2 size={15}/> Remove</button><span className="preview-number">PHOTO {String(selected+1).padStart(2,'0')}</span></div><div className="location-editor"><div className="location-title"><div><h3>{current.location ? (current.gps?'Location found automatically':'Location set') : current.gpsStatus==='unreadable'?'Couldn’t read the photo’s GPS':'No GPS location in this photo'}</h3><p>{current.location ? (current.gps?'The photo’s GPS placed this pin. You can publish without changing it.':'Pin placed. You can move it with another click.') : current.gpsStatus==='unreadable'?'Try the original camera file, search for the place, or set a pin on the map.':'This file has no saved GPS coordinates. Search for the place below, choose a geotagged original, or place a pin.'}</p></div><span className={`location-status ${current.location?'set':''}`}>{current.location?<Check size={17}/>:<MapPin size={17}/>}</span></div><LocationSearch key={`search-${current.id}`} onSelect={place=>update({location:{lat:place.lat,lng:place.lng},gps:false,locationFocus:place})}/><Map key={current.id} value={current.location} focus={current.locationFocus} onChange={location=>update({location,gps:false})} className="editor-map"/><CoordinateFields value={current.location} onChange={location=>update({location,gps:false})}/><label htmlFor="caption">A little story for the reveal <span>(optional)</span></label><input id="caption" placeholder="That café we nearly walked past…" maxLength={200} value={current.caption} onChange={e=>update({caption:e.target.value})}/><small>Friends see this after they guess.</small></div></div>}</div>}
    {error&&<p className="error" role="alert">{error}</p>}<div className="publish-bar"><div><LockKeyhole size={18}/><span>Locations stay secret until each guess.<br/><small>We remove location metadata from shared photos.</small></span></div><button className="button" disabled={busy||preparing||!photos.length||!!missing||!title.trim()||!hostName.trim()}>{busy?<><LoaderCircle className="spin" size={18}/> Publishing your trip…</>:<>Create & share trip <ArrowRight size={18}/></>}</button></div>{missing>0&&<p className="missing-note">{missing} {missing===1?'photo has':'photos have'} no detected GPS location. Set {missing===1?'its location':'their locations'} or choose geotagged photos to publish.</p>}</form>
  </main>;
}

function CoordinateFields({value,onChange}) {
  const [lat,setLat]=useState(value?value.lat.toFixed(5):''),[lng,setLng]=useState(value?value.lng.toFixed(5):'');
  useEffect(()=>{setLat(value?value.lat.toFixed(5):'');setLng(value?value.lng.toFixed(5):'');},[value?.lat,value?.lng]);
  function apply(a,b){if(a.trim()&&b.trim()&&Number.isFinite(Number(a))&&Number.isFinite(Number(b))&&Math.abs(Number(a))<=90&&Math.abs(Number(b))<=180)onChange({lat:Number(a),lng:Number(b)});}
  return <details className="coordinates"><summary>{value?`${value.lat.toFixed(4)}°, ${value.lng.toFixed(4)}°`:'Or enter coordinates'} <ChevronRight size={13}/></summary><div><label>Latitude<input type="number" step="any" min="-90" max="90" placeholder="−90 to 90" value={lat} onChange={e=>setLat(e.target.value)} onBlur={()=>apply(lat,lng)}/></label><label>Longitude<input type="number" step="any" min="-180" max="180" placeholder="−180 to 180" value={lng} onChange={e=>setLng(e.target.value)} onBlur={()=>apply(lat,lng)}/></label><button type="button" className="button small outline" onClick={()=>apply(lat,lng)}>Set pin</button></div></details>;
}

function Game({id,navigate,notify}) {
  const [game,setGame]=useState(null),[run,setRun]=useState(null),[name,setName]=useState(localStorage.getItem('tg_player_name')||'');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[pin,setPin]=useState(null),[result,setResult]=useState(null),[board,setBoard]=useState([]),[loading,setLoading]=useState(true);
  useEffect(()=>{api(`/games/${id}`).then(data=>{setGame(data.game);setRun(data.run);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[id]);
  useEffect(()=>{if(run?.completed){api(`/games/${id}/leaderboard`).then(setBoard).catch(e=>notify(e.message));}},[run?.completed,id]);
  async function join(e){e.preventDefault();setBusy(true);setError('');try{const data=await api(`/games/${id}/join`,json('POST',{name}));localStorage.setItem('tg_player_name',name);setRun(data);}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function guess(){if(!pin)return;setBusy(true);setError('');try{const data=await api(`/games/${id}/guess`,json('POST',{...pin,round:run.round}));setResult(data.result);setRun(data.run);}catch(e){setError(e.message);}finally{setBusy(false);}}
  if(loading)return <div className="loading-page"><LoaderCircle className="spin"/> Finding your adventure…</div>;
  if(!game)return <main className="narrow-page"><Compass size={38}/><h1>A little off the map.</h1><p role="alert">{error}</p><button className="button" onClick={()=>navigate('/')}>Back home</button></main>;
  if(!run)return <main className="join-page"><div className="join-art"><img src="/images/mountains.jpg" alt="Sunlit mountain peaks"/><div><span className="eyebrow">YOU’RE INVITED TO GET A LITTLE LOST</span><h2>Every photo<br/>has a place.<br/><em>Find it.</em></h2></div><span className="join-art-footer"><Globe2 size={18}/> Your next adventure starts with a guess.</span></div><div className="join-form"><span className="pill"><Users size={15}/> {game.demo?'A taste of the adventure':`An adventure by ${game.hostName}`}</span><h1>{game.title}</h1><p>{game.demo?'Three iconic places. One world map. Give it your best shot.':`${game.hostName} has ${game.rounds} ${game.rounds===1?'photo':'photos'} for you. Look for clues, drop a pin, and see how close you can get.`}</p><div className="game-facts"><span><Camera size={18}/><b>{game.rounds}</b> rounds</span><span><Trophy size={18}/><b>{(game.rounds*5000).toLocaleString()}</b> possible points</span></div><form onSubmit={join}><label htmlFor="player-name">What should we call you?</label><input id="player-name" placeholder="Your name or legendary nickname" value={name} onChange={e=>setName(e.target.value)} maxLength={24} required autoComplete="nickname"/>{error&&<p className="error" role="alert">{error}</p>}<button className="button full" disabled={busy}>{busy?<LoaderCircle className="spin" size={18}/>:<Compass size={18}/>} Let’s explore <ArrowRight size={18}/></button></form><p className="small-note"><LockKeyhole size={13}/> No sign-up. Your progress is saved in this browser.</p></div></main>;
  if(run.completed&&!result)return <main className="results-page"><div className="results-hero"><span className="success-icon"><Trophy size={35}/></span><span className="eyebrow">SOME GOOD GUESSES. SOME GREAT MEMORIES.</span><h1>Well travelled,<br/><em>{run.name}.</em></h1><p>You’ve explored “{game.title}”. Here’s how you did.</p><div className="total-score">{run.score.toLocaleString()}<span>/ {(game.rounds*5000).toLocaleString()} points</span></div><div className="center-buttons"><button className="button" onClick={()=>copyLink(id,notify)}>Challenge a friend <ArrowUpRight size={18}/></button><button className="button outline" onClick={()=>navigate('/')}>Back home</button></div></div><div className="results-columns"><section className="panel round-summary"><h2>Your journey, in pins.</h2>{run.results.map((r,i)=><div className="summary-row" key={i}><img src={`/api/games/${id}/photos/${i}`} alt={`Photo from round ${i+1}`}/><div><span className="eyebrow">ROUND {i+1}</span><p>{formatDistance(r.distance)} away</p></div><strong>{r.score.toLocaleString()}<small> pts</small></strong></div>)}</section><section className="panel leaderboard"><div className="leaderboard-title"><h2>The bragging board</h2><Trophy size={23}/></div><p>A little competition brings everyone closer.</p>{board.length ? board.map((entry,i)=><div key={`${entry.name}-${i}`} className="leaderboard-row"><span className={`rank ${i===0?'first':''}`}>{i===0?<Trophy size={16}/>:String(i+1).padStart(2,'0')}</span><b>{entry.name}</b><span>{entry.score.toLocaleString()} <small>pts</small></span></div>) : <p className="small-note">Scores appear here when players finish.</p>}<button className="text-button" onClick={()=>api(`/games/${id}/leaderboard`).then(setBoard).catch(e=>notify(e.message))}>Refresh scores <ArrowRight size={15}/></button></section></div></main>;
  const round=result?result.round:run.round;
  return <main className="play-page"><div className="play-heading"><div><span className="eyebrow">{game.title}</span><h1>{result?'The moment of truth.':'Somewhere in the world…'}</h1></div><div className="play-stats"><span><Camera size={17}/> Round <b>{round+1}</b> / {game.rounds}</span><span><Trophy size={17}/><b>{run.score.toLocaleString()}</b> pts</span></div></div><div className="round-progress">{Array.from({length:game.rounds},(_,i)=><span key={i} className={i<run.round?'done':i===round?'current':''}/>)}</div><div className="game-layout"><section className="game-photo"><img src={`/api/games/${id}/photos/${round}`} alt={`Mystery location for round ${round+1}`}/><span className="photo-label"><Camera size={14}/> {result?'ONE MORE MEMORY, FOUND':'LOOK A LITTLE CLOSER'}</span><span className="photo-round">{String(round+1).padStart(2,'0')}</span></section><section className="guess-panel panel"><div className="guess-panel-header"><span className="step-icon">{result?<Flag size={21}/>:<MapPin size={22}/>}</span><div><h2>{result?(result.distance<10?'You know your way around!':result.distance<500?'A pretty good hunch.':'A world of possibility.'):'Where’s your hunch?'}</h2><p>{result?'Your guess, meet the real location.':'Scroll to zoom, drag to explore, click to drop a pin.'}</p></div></div><Map key={`${round}-${!!result}`} value={result?result.guess:pin} actual={result?.actual} onChange={result?undefined:setPin} className="guess-map"/>{result?<div className="round-result"><div className="map-legend"><span><i className="guess-dot"/> Your guess</span><span><i className="actual-dot"/> Actual location</span></div><div className="result-numbers"><div><span>DISTANCE</span><b>{formatDistance(result.distance)}</b></div><div><span>ROUND SCORE</span><b>+{result.score.toLocaleString()} <small>pts</small></b></div></div>{result.caption&&<p className="reveal-caption">{result.caption}</p>}<button className="button full" onClick={()=>{setResult(null);setPin(null);setError('');window.scrollTo(0,0);}}>{run.completed?'See the final scores':'Next photo'} <ArrowRight size={18}/></button></div>:<div className="guess-controls"><CoordinateFields value={pin} onChange={setPin}/><button className="button full" disabled={!pin||busy} onClick={guess}>{busy?<LoaderCircle className="spin" size={18}/>:<MapPin size={17}/>} {pin?'Lock in your guess':'Drop a pin to make your guess'} {pin&&<ArrowRight size={17}/>}</button><small>You get one guess. Make it a good one.</small></div>}{error&&<p className="error" role="alert">{error}</p>}</section></div></main>;
}

createRoot(document.getElementById('root')).render(<App/>);
