// Planning model in USD, not a spending cap. Rates and assumptions: docs/COSTS-AND-LIMITS.md.
const sessions=Number(process.argv[2]||1000),storedTrips=Number(process.argv[3]||100),playersPerRoom=Number(process.argv[4]||5);
if(!Number.isFinite(sessions)||sessions<0||!Number.isFinite(storedTrips)||storedTrips<0||!Number.isFinite(playersPerRoom)||playersPerRoom<1||playersPerRoom>21)throw Error('Usage: node scripts/estimate-costs.mjs [monthlyPlayerSessions] [storedTrips] [browsersPerRoom:1..21]');
// 40 SSE reconnects + 100 draft moves + 10 locks + 10 readiness + photos/pages/assets.
const requests=sessions*220+25920,readOps=sessions*700,writeOps=sessions*125,egressGiB=sessions*12/1024,photoGiB=storedTrips*10*.5/1024;
const costs={photoStorage:photoGiB*.023,photoReads:sessions*20/1000*.0004,egress:egressGiB*.12,firestoreReads:Math.max(0,readOps-50000*30)/100000*.039,firestoreWrites:Math.max(0,writeOps-20000*30)/100000*.117,ttlDeletes:sessions*2/100000*.013,cloudflare:requests/30>100000?5+Math.max(0,requests-10e6)/1e6*.30+Math.max(0,requests*3-30e6)/1e6*.02:0};
// One or two occupied instances per room. Concurrent rooms sharing an instance cost less.
const roomSeconds=sessions/playersPerRoom*1800;
const compute=instances=>{const seconds=roomSeconds*instances;return Math.max(0,seconds*.0000336-4.32)+Math.max(0,seconds*.0000035-.90)+Math.max(0,requests-2e6)/1e6*.40;};
const other=Object.values(costs).reduce((sum,cost)=>sum+cost,0),round=n=>Number(n.toFixed(2));
console.log(JSON.stringify({assumptions:{playerSessionsPerMonth:sessions,storedTrips,playersPerRoom,minutesPerSession:30,draftMovesPerPhoto:10,photosPerTrip:10,averagePhotoMiB:.5,transferMiBPerSession:12,instancesPerRoom:[1,2],days:30},usage:{requests,reads:readOps,writes:writeOps,averageDailyRequests:Math.ceil(requests/30),roomHours:round(roomSeconds/3600),egressGiB:round(egressGiB)},costUSD:Object.fromEntries(Object.entries(costs).map(([k,v])=>[k,round(v)])),cloudRunUSD:[round(compute(1)),round(compute(2))],modelTotalUSD:[round(other+compute(1)),round(other+compute(2))],exclusions:'Domain, tax, builds/artifacts, logs, uploads, database storage, startup overhead, unusual destinations, abuse and repeated downloads. Daily quotas assume evenly spread traffic and otherwise unused free allowances. Sustained pin dragging or polling fallback increases requests/read/write costs.'},null,2));
